// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IdentityNative.Models;

public partial class GRUPOS_PERMISSOES
{
    [Key]
    public int ID { get; set; }

    public int? GRUPO_ID { get; set; }

    public int? PERMISSAO_ID { get; set; }

    [ForeignKey("GRUPO_ID")]
    [InverseProperty("GRUPOS_PERMISSOES")]
    public virtual GRUPOS GRUPO { get; set; }

    [ForeignKey("PERMISSAO_ID")]
    [InverseProperty("GRUPOS_PERMISSOES")]
    public virtual PERMISSOES PERMISSAO { get; set; }
}