// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IdentityNative.Models;

public partial class GRUPOS_USUARIOS
{
    [Key]
    public int ID { get; set; }

    public int? USUARIO_ID { get; set; }

    public int? GRUPO_ID { get; set; }

    [ForeignKey("GRUPO_ID")]
    [InverseProperty("GRUPOS_USUARIOS")]
    public virtual GRUPOS GRUPO { get; set; }

    [ForeignKey("USUARIO_ID")]
    [InverseProperty("GRUPOS_USUARIOS")]
    public virtual USUARIOS USUARIO { get; set; }
}