// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IdentityNative.Models;

public partial class PERMISSOES
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string DESCRICAO { get; set; }

    public bool? ATIVO { get; set; }

    [InverseProperty("PERMISSAO")]
    public virtual ICollection<GRUPOS_PERMISSOES> GRUPOS_PERMISSOES { get; set; } = new List<GRUPOS_PERMISSOES>();
}