// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IdentityNative.Models;

public partial class USUARIOS
{
    [Key]
    public int ID { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string NOME { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string EMAIL { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string SENHA { get; set; }

    public bool? ATIVO { get; set; }

    [InverseProperty("USUARIO")]
    public virtual ICollection<GRUPOS_USUARIOS> GRUPOS_USUARIOS { get; set; } = new List<GRUPOS_USUARIOS>();
}